// console.log(99*123);
// console.log(22+23+44);
// console.log(1000-17);
// console.log(12345/250);
// console.log((1234 + 57) * 3 - 31 / 4);
// console.log(8/(1+3));
// //try it yourself page 17
// console.log((15+9)*2); 
// let nick;
// let age = 12;
// console.log(nick);
// console.log(age);
// age = 13;
// console.log(age);
// let numberOfSimblings = 1+3;
// let numberOfCandles = 8;
// console.log("The answer is", numberOfCandles / numberOfSimblings);
// let secondsInAMinute = 60;
// let minutesInAnHour = 60;
// let secondsInAnHour = secondsInAMinute * minutesInAnHour;
// let hoursInADay = 24;
// let secondsInADay = secondsInAnHour * hoursInADay;
// let daysInAYear = 365;
// let secondsInAYear = secondsInADay * daysInAYear;
// age = 52;
// console.log("I am", age*secondsInAYear,"seconds old");
// let highFives = 0;
// ++highFives;
// console.log(highFives);
// ++highFives;
// console.log(highFives);
// --highFives;
// console.log(highFives);
// let highFives = 4;
// console.log(--highFives + 5);
// let x = 10;
// x = x + 5;
// console.log(x);
// let x = 10;
// x += 5;
// console.log(x);
// let score = 10;
// score += 7;
// score -= 3;
// console.log(score);
//try it out page 23
// let balloons = 100;
// balloons *= 2;
// console.log(balloons);
// balloons /= 4;
// console.log(balloons); 
// let numberNine = 9;
// let stringNine = "9";
// console.log(numberNine + numberNine);
// console.log(stringNine+stringNine);
// console.log(stringNine+numberNine);
// var greeting = "Hello";
// var myName = "Nick";
// console.log(greeting + " " + myName);

// let x = "Supercalifragilisticexpialidociousf";
// // console.log(x.length);
// let myName = "Nick";
// console.log(myName.indexOf("c"));
// let codeWord1 = "are";
// let codeWord2 = "tubas";
// let codeWord3 = "unsafe";
// let codeWord4 = "?!";
// let code = codeWord1[1] + codeWord2[1] + codeWord3[1] + codeWord4[1];
// console.log(code);
// console.log("A string".slice(2));
// let longString = "My long string is long";
// console.log(longString.slice(3, 14));
// console.log(longString.slice(3));
// console.log("Hello there.How are you doing?".toUpperCase());
// console.log("Hello there.How are you doing?".toLowerCase());
// let x = "hELlo THERE, hOW ARE yOu doINg?";
// x = x[0].toUpperCase() + x.slice(1).toLowerCase();
// console.log(x);
// let javascriptIsCool = true;
// console.log(javascriptIsCool);
// let hadShower = false;
// let hasBackpack = true;
// let goToSchool = hadShower && hasBackpack;
// console.log(goToSchool);
// var hasApple = false;
// var hasOrange = false;
// let goToSchool = hasApple || hasOrange;
// console.log("go to school?",goToSchool);
// var isWeekend = false;
// console.log("need To Shower Today?",!isWeekend);
// let isWeekend = confirm("Is it weekend?");
// let hadShower = confirm("Did you have a shower?");
// let hasApple = confirm("Do you have an apple?");
// let hasOrange = confirm("Do you have an orange?");
// let shouldGoToSchool = !isWeekend && hadShower &&(hasApple || hasOrange);
// alert("Should you go to school? " + shouldGoToSchool); 
// let height = prompt("What is your height?");
// let heightRestriction = 60;
// alert("Is allowed on the ride? "+ (height >= heightRestriction) );
// let height = prompt("What is your height?");
// let heightRestriction = 48;
// alert("Is allowed on the ride? "+ (height  <= heightRestriction) );
// let mySecretNumber = 5;
// let chicoGuess = 3;
// alert("Chico " + (mySecretNumber === chicoGuess))
// let harpoGuess = 7;
// alert("Harpo " + (mySecretNumber === harpoGuess))
// let grouchoGuess = 5;
// alert("Groucho " + (mySecretNumber === grouchoGuess))
// let mySecretNumber = 5; 
// alert("You guessed correctly? " + (mySecretNumber === (prompt("guess the number:"))))
// var stringNumber = "5";
// var actualNumber = 5;
// console.log(stringNumber == actualNumber);
// //try it out posage 37
let age = prompt("What is your age?");
let accompanied = confirm("Are you accompanied by an adult?");
alert("you are allowed to watch? " + (age >=13 || accompanied));

